### ISSUE TITLE
'Landscape Images JS Tweaks (beta, working, some layout quirks with shelves)'

### ISSUE THREAD

**Issue by CitizenFoffie** [Jonius7/SteamUI-OldGlory#48] opened 2022-05-27 03:20 UTC
![image](https://user-images.githubusercontent.com/40131823/170622542-a14a923d-f08f-492d-9584-541ea507a1a3.png)

**Comment by Jonius7** [comment] 2022-07-30 00:34
Closed as cannot seem to reproduce the issue

**Comment by Cascabel-dev** [comment] 2022-11-27 08:41
I am also having this same issue 
![image](https://user-images.githubusercontent.com/85851257/204126325-610015ab-a24d-4512-b8fb-9eca12263de4.png)

**Comment by Cascabel-dev** [comment] 2022-11-27 08:43
I have tried nearly every combination of boxes and settings, I always hit the same error.  I am using Arch Linux, and have installed all of the required pip modules, but still no dice.  I get no terminal output of elaboration.  I have tried running the tool as root (sudo) and as a standard user.  Neither make any progress.
Thanks so much for your time.

**Comment by Cascabel-dev** [comment] 2022-11-27 18:04
I've been sitting here messing with the issue a bit.  Rolling back to R5.10.4-pre1 and commenting out lines 51 and 119 in manager.py, as well as the line pertaining to verification in backend.py (somewhere in the mid 800s if recollection serves, I can't quite remember), and the issue seems to be resolved to a partial extent.  Some settings no longer work, and the program still throws a myriad of errors, but most of the tweaks seem to be working properly.

**Comment by Jonius7** [comment] 2023-02-10 07:19
Should be fixed in [5.10.7](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.10.7)

**Closed by Jonius7** 2023-02-10 07:19 UTC
Labels: GUI
